### ISSUE TITLE
Добавить php7.0-xml в скрипт

### ISSUE THREAD

**Issue by mezhevikin** [globalmac/Larascale#1]
Привет. После установки при первом _composer update_ потребовал "ext-dom".

```
Your requirements could not be resolved to an installable set of packages.
    - phpunit/phpunit 4.8.9 requires ext-dom 
```

Решил проблему так:
`sudo apt-get install php7.0-xml`

Может имеет смысл добавить зависимость php7.0-xml в скрипт?

_Ubuntu 14.04 64bit
vscale.io_

**Comment by globalmac** [comment]
Спасибо! Добавил.
